### ISSUE TITLE
Error on IE < 11

### ISSUE THREAD

**Issue by Colir** [galambalazs/smoothscroll-for-websites#1]
When watching a page with smoothscroll script, 
IE (under version 11) throw an error on this

if(x=new j(i),x.observe(t,c),X.offsetHeight<=n)

thanks

**Comment by gblazex** [comment]
fixed in the new version 1.3.9, thanks
https://github.com/galambalazs/smoothscroll-for-websites/commit/9afaf2276600d2f09e626a0bdbe9c5db7ccefacf
