### ISSUE TITLE
Smothscroll spiking timelines on parallax scripts

### ISSUE THREAD

**Issue by danyj** [galambalazs/smoothscroll-for-websites#11]
@galambalazs  hello bud , I am working on parallax script since few days and was sure that 
scroll lag was inside my script but I just found out that smothscroll is spiking the timelines on elements that perform transitions on scroll, 

This is my timeline with smooth
![smooth](https://cloud.githubusercontent.com/assets/2340172/9773463/a232407e-5742-11e5-996b-48d20c70189e.jpg)

and this is timeline without 

![6hpwobt](https://cloud.githubusercontent.com/assets/2340172/9773522/0e98d494-5743-11e5-9e4c-9f5689df7231.png)

I setup this git for you 
https://jsfiddle.net/ypyemoxb/
so that you can see the timeline issue 
by using 
https://gist.github.com/Warry/4254579

even his timeline is spiking and his script is very lean. 

But my script is experiencing lags ( delays ) when scrolling. 
Since my script is not public I would be glad to sent it over to you if you like. 

Let me know

**Comment by danyj** [comment]
Here is video of my script ,  you can see the jumps
www.screencast.com/t/82xmcmApYrbK

**Comment by gblazex** [comment]
Hey @danyj!

Sure send me an email, it's on my profile: https://github.com/galambalazs

Also please include your hardware specs.

The jsfiddle is way below budget for me (1-2 ms total for each frame).

**Comment by danyj** [comment]
Sent bud. from youjoomlallc  at gmail ,

**Comment by gblazex** [comment]
Cool, I'll take a look at it. Just as a quick note (for the jsfiddle):

I can get 1 single spike (1 tall bar) every once in a while with a ton of rasterization. But I get the same result on my Mac scrolling with the trackpad so it may be a Chrome renderer issue.

**Comment by danyj** [comment]
ie edge on w10 is bit worse, seems like it stops at sections

**Comment by gblazex** [comment]
In the meantime you could test it with a bare bones scroll script pasted into the Console:

```
requestAnimationFrame(function step() {
  window.scrollBy(0, 20); // the delta can be bigger to make it go faster
  requestAnimationFrame(step);
});
```

See if this triggers the same spikes for you.
(it does for me)

**Comment by danyj** [comment]
sorry mate I shut down watching a movie. 2 am here . will pick up with you tomorow if you dont mind.

**Comment by danyj** [comment]
@galambalazs   yes you right , it spikes and jumps with 

requestAnimationFrame(function step() {
  window.scrollBy(0, 20); // the delta can be bigger to make it go faster
  requestAnimationFrame(step);
});

**Comment by gblazex** [comment]
I suggest you open a new issue for the Chrome team:
https://code.google.com/p/chromium/issues/list

Cheers

**Comment by danyj** [comment]
Bud , check mail please.
