### ISSUE TITLE
Add to npm repository?

### ISSUE THREAD

**Issue by dlong500** [galambalazs/smoothscroll-for-websites#12]
For those of us who use npm with gulp/webpack/etc it would be nice to be able to pull this module directly from npm.  Any chance of getting it published there (especially since there is already a package.json file)?

I guess the npm name would have to be difference than smoothscroll because there is already a module with that name.

**Comment by gblazex** [comment]
Isn't it possible to grab this repo in npm via the Git url?

I'm not sure all the services that use package.json currently, changing the name in that file could  break things.

**Comment by TrySound** [comment]
@galambalazs To use exact version of package with repo, could you add git tags for key commits?

**Comment by gblazex** [comment]
added https://github.com/galambalazs/smoothscroll-for-websites/tags

**Comment by TrySound** [comment]
Thanks!

**Comment by dlong500** [comment]
It would still be nice to add this to NPM directly somehow.  While you can grab stuff directly from a git URL via NPM commands you have to specify the tag manually and can't rely on semantic versioning rules.  Also, NPM won't show the latest version and also re-installs the module on every `npm update` command.

So basically I have to manually check the Github repo every so often and then manually update my dependency to the latest version if a new release has occurred.  And I have to live with the package being re-installed every time I update any other NPM modules.  Not the end of the world but still somewhat annoying.  If I ended up having several modules with direct git URLs I can imagine it would get old real quick.

**Comment by gblazex** [comment]
I'm happy to add it to NPM _if_ we can ensure compatilbity with all the other services using `package.json` 

AFAIK the _smoothscroll_ name was taken in NPM

**Comment by dlong500** [comment]
Yeah, the issue with the name in `package.json` is what I'm not sure how to handle.  What services are currently actually using the name in `package.json`?  Since you have a separate bower config file I assume bower doesn't need the name in `package.json` to be the same.  Could a public scoped NPM package work? (see https://docs.npmjs.com/misc/scope).

**Comment by dlong500** [comment]
Have you had a chance to look into this?  I'm trying to figure out what things other than NPM actually need the `package.json` file.  Could it be as simple as just changing the name in `package.json` and then uploading to NPM?

**Comment by gblazex** [comment]
One of them that I remember was `cdnjs`. I asked for advice here: https://github.com/galambalazs/smoothscroll-for-websites/issues/5

**Comment by dlong500** [comment]
Would it be possible to change the name in cdnjs to something that is available in npm?  It seems like that should theoretically be possible without disrupting existing users by just leaving the old library name in cdnjs for now as well, but I guess we'll see how they respond to your query.

I could always fork the repo, change the package name, and upload to npm but then I'd have to manually pull any updates you make, so I'd certainly rather have it be on npm directly from the source.  Thanks for the effort.

**Comment by gblazex** [comment]
Yeah, better not post forks to package managers cause then we'll have sites stuck on outdated versions in the wild again.

See: https://github.com/galambalazs/smoothscroll/issues/111

**Comment by gblazex** [comment]
https://www.npmjs.com/package/smoothscroll-for-websites

**Comment by dlong500** [comment]
Awesome!  Thanks.
