### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of undefined

### ISSUE THREAD

**Issue by jacksun101** [galambalazs/smoothscroll-for-websites#17]
I am using SmoothScroll with Cube Portfolio plugin. SmoothScroll.js shows the error at line #401 when I hit the Left/Right Arrow button on the keyboard after Cube Portfolio load in the Ajax content. The example of Cube plugin is as below.

http://scriptpie.com/cubeportfolio/live-preview/templates/01-juicy-projects/#cbp=ajax-juicy-projects/project1.html

**Comment by gblazex** [comment]
Thanks i'll look into it

**Comment by gblazex** [comment]
I wasnt able to reproduce on the page you linked. Tried hitting the left/right arrow keys, also opening images and hitting arrow keys. No error shown for me.

**Comment by jacksun101** [comment]
Sorry, they, cubeportfolio, seems have rebuilt the examples without SmoothScroll now. That's ok, I will close this for now. I will find time to see if I could reproduce and let you know, thank you so much.
