### ISSUE TITLE
define.amd

### ISSUE THREAD

**Issue by m0hamm4dElmi** [galambalazs/smoothscroll-for-websites#20]
Hey,
Please check line 712:
if (typeof define === 'function' && define.amd)

What is define.amd?
It seems it must be deleted, right?

**Comment by TrySound** [comment]
@m0hamm4dElmi Nope. It specifies that used `amd` compatible api.

**Comment by gblazex** [comment]
@m0hamm4dElmi Does it cause problems for you somewhere? Or is this a hypothetical question?

**Comment by gblazex** [comment]
See: https://github.com/amdjs/amdjs-api/blob/master/AMD.md#defineamd-property-

> ### define.amd property
> 
>  To allow a **clear indicator** that a global `define` function **conforms to the AMD API**, any global define function SHOULD have a property called `amd` whose value is an object. This helps avoid conflict with any other existing JavaScript code that could have defined a `define()` function that does _not_ conform to the AMD API.

**Comment by m0hamm4dElmi** [comment]
@TrySound , @galambalazs Thank you so much,
@galambalazs this is a hypothetical question :)
and sorry for the delay.
