### ISSUE TITLE
IE support

### ISSUE THREAD

**Issue by Maximilianos** [galambalazs/smoothscroll-for-websites#21]
In the "First Run" part: 

``` javascript
/***********************************************
 * FIRST RUN
 ***********************************************/

var userAgent = window.navigator.userAgent;
var isEdge    = /Edge/.test(userAgent); // thank you MS
var isChrome  = /chrome/i.test(userAgent) && !isEdge; 
var isSafari  = /safari/i.test(userAgent) && !isEdge; 
var isMobile  = /mobile/i.test(userAgent);
var isEnabledForBrowser = (isChrome || isSafari) && !isMobile;
```

Why is it Chrome/Safari only? IE could use some smoothscrolling love as well, or are there any issues I may not be aware of?

**Comment by gblazex** [comment]
IE has built in smooth scrolling as far as I know
(Meaning one tick of mouse wheel is not just a discrete 100px jump but an animation)

**Comment by Maximilianos** [comment]
I think you may be able to enable it as a configuration setting, though I am not aware exactly how, but I am on a Windows 7 PC right now and by default IE11 is not animating.

**Comment by gblazex** [comment]
According to this it's On by default since Windows 8
http://stackoverflow.com/questions/29416448/how-to-disable-smooth-scrolling-in-ie11

Couldn't find other references yet. It's been a while since I used 7, so I might have remembered it wrong.

Can you look for more references if it's indeed W 8+ only?

**Comment by Maximilianos** [comment]
sure, will check n let u know

**Comment by Giovancruz** [comment]
I use Windows 8.1 with the browser Edge and the SmoothScroll not worked.

**Comment by gblazex** [comment]
will check, thanks

**Comment by dbdev** [comment]
Hi,

I'm also interested in the issue for Windows 8.1, any help will be appreciated.

Thanks

**Comment by gblazex** [comment]
I'll be able to look into this over the weekend.

**Comment by gblazex** [comment]
It seems to me that Edge is only available for Windows 10.

http://stackoverflow.com/questions/31781292/can-i-download-use-microsoft-edge-in-windows-8-1
https://www.quora.com/Can-I-download-Microsoft-Edge-for-my-Windows-8-1-laptop

Is it what you guys meant? Windows 10 & Edge?

@Giovancruz @dbdev 

In case of Edge there's built in smooth scrolling.

**Comment by gblazex** [comment]
@Maximilianos  I just checked and Windows 7 doesn't indeed have the kind of smooth scrolling I remembered. It does have something _called_ "smooth scrolling" but it's not really smooth, and the animation is almost nonexistent.

Windows 8 has a totally different kind of smooth scrolling, which was good enough not to be messed with.

I'll think about enabling this project for Win7 + IE 11 specifically.

Not sure about older versions of IE though.

**Comment by dbdev** [comment]
Just keep me posted guys on the IE issue, it would be nice to get something similar to the Mac version.

**Comment by gblazex** [comment]
@dbdev You should have smooth scrolling in IE 11 under Windows 8.1.

**Comment by dbdev** [comment]
Hi again,

do you guys have the possibility to check is there is an issue with Windows 8 + Chrome and the scrolling with the mouse wheel?

Thanks a lot for a response

**Comment by Maximilianos** [comment]
I have W7 and W10 but no 8.

**Comment by Maximilianos** [comment]
@galambalazs thanks for the effort, let me know if I can help with something

**Comment by dbdev** [comment]
Does the wheel scroll in Chrome works correctly in those versions?

**Comment by Maximilianos** [comment]
in Chrome? yes definetely.
My issue was for IE on W7

**Comment by dbdev** [comment]
Thanks for checking.

**Comment by jishei-128** [comment]
Regarding IE 11 i've got an issue, that when the background-Image is fixed, the Image is somehow shaking when Scrolling with the mouse-wheel. Is that a known issue?

**Comment by gblazex** [comment]
Windows 7, 8, 10 ?

**Comment by kostiantyn-petlia** [comment]
Hi.

I have Win7 & IE11 & try to fix:

```
var isExplorer    = /Trident\/|MSIE /.test(userAgent); // IE
var isEnabledForBrowser = (isChrome || isSafari || isExplorer) && !isMobile;
```

But if I press key down in IE11 I got error here:

```
    // our own tracked active element could've been removed from the DOM
    if (!document.contains(activeElement)) {
        activeElement = document.activeElement;
    }
```

I think will be good if to support and the fuc... IE :) Win7 will live few years yet.

**Comment by gblazex** [comment]
what error?

**Comment by kostiantyn-petlia** [comment]
Like this: https://github.com/skatejs/skatejs/issues/153 = "document.contains doesn't exist"

**Comment by gblazex** [comment]
Right. Seems like easy to fix:

```
if (!document.body.contains(activeElement)) {
    activeElement = document.activeElement;
}
```

I'll update the repo with this in the future, but in the meantime you can use this.

see this IE bug: https://connect.microsoft.com/IE/feedback/details/780874/node-contains-is-incorrect

**Comment by gblazex** [comment]
added IE 11 Win 7 support in v1.4.4, also fixed this bug above.

Let me know guys how it works

cc @Maximilianos @artfulcat

**Comment by kostiantyn-petlia** [comment]
All is right. Thx.
