### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of undefined

### ISSUE THREAD

**Issue by nxrighthere** [galambalazs/smoothscroll-for-websites#22]
> SmoothScroll.js:401 Uncaught TypeError: Cannot read property 'clientHeight' of undefined

Windows 10, Chrome 47

**Comment by gblazex** [comment]
Which site? How could I reproduce?

**Comment by nxrighthere** [comment]
Similar issue https://github.com/galambalazs/smoothscroll-for-websites/issues/38
