### ISSUE TITLE
Scrolling issue on zoomed website on Chrome

### ISSUE THREAD

**Issue by arturstarodaj** [galambalazs/smoothscroll-for-websites#27]
When you zoom out on newest Chrome, and go to a subpage, the library crashes and disables scroll. As the result neither smoothscrolling and natoie browser scrolling are working.

**Comment by gblazex** [comment]
Can you show me a concrete page that I can see?
Thanks

**Comment by gblazex** [comment]
feel free to reopen if you have more details
