### ISSUE TITLE
Unable to tab through radio input

### ISSUE THREAD

**Issue by evheny0** [galambalazs/smoothscroll-for-websites#29]
Tab through radio input is not working currently. As I can see in keydown event handler, there is no case for arrow keys on radio buttons

**Comment by gblazex** [comment]
You are right. I can see this in Chrome (never used the feature myself though). 
Safari doesn't navigation with arrow keys in radio by default.

Can you test this in other browsers as well?

Thanks for reporting

**Comment by galambalazs** [comment]
Can you test with the latest version on `master`?
