### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by petrck** [galambalazs/smoothscroll-for-websites#32]
Hi, first of all i want to thank you for this component, i found it very useful. I would like to ask you if it is possible to re-init smoothScroll with use of turbolinks. After second page:load with turbolinks (no page refresh), page scroll is completely blocked. Without the smoothScroll effect scrolling works fine.

Thanks for your help

**Comment by gblazex** [comment]
Did you try calling `SmoothScroll()` after navigation?

See Public API:
https://github.com/galambalazs/smoothscroll-for-websites/wiki

**Comment by petrck** [comment]
Of course. Page scroll is still blocked. This is my Re-init function:

```
function componentInit() {
//init material design
    $.material.init();

    //init texarea autosize
    autosize($('textarea'));

    //init parallax
    $('.parallax-window').parallax();

    //init smooth scroll
    SmoothScroll();
...
}
$(function () {
    componentInit();

});

$(document).on('page:load', function () {
    componentInit();
});
```

**Comment by gblazex** [comment]
Can you post a bare bones example on jsfiddle or jsbin?

**Comment by petrck** [comment]
The all scripts are loading with systemjs and it is little complicated, but, i tested this: https://github.com/simov/simplr-smoothscroll and it works fine. Scrolling is not too perfectly, like your solution, but maybe help? Turbolinks, ale here: https://github.com/turbolinks/turbolinks-classic

**Comment by richpeck** [comment]
Ditto on this - having exactly the same problem

**Comment by richpeck** [comment]
Turbolinks is used in Rails to make pages load faster.

If the assets are the same for the new request, it loads a new `<body>` tag, leaving `<head>` as it was.

Because this script has been designed around window load (IE when the script is loaded), it won't work if Turbolinks pulls a page without refreshing the header. 

The solution is to change the init procedure, although I've not looked into it enough to do this yet

**Comment by gblazex** [comment]
Thanks for reporting guys.

I know about Turbolinks, but I don't have time to look into this issue right now. PRs are welcome.

Also hasn't turbolinks went through some major changes with the latest Rails?

**Comment by richpeck** [comment]
Yes it's changed but the dev side is still pretty much the same

I'll look into it and get back

**Comment by gblazex** [comment]
Much appreciated. Thanks Rich!

**Comment by richpeck** [comment]
Submitted PR for this https://github.com/galambalazs/smoothscroll-for-websites/pull/36

**Comment by gblazex** [comment]
Thanks for caring so deeply about this Rich. 

Can you make a PR that's focused on fixing the Turbolinks issue?

I feel strongly about keeping this project simple and dependency free.

**Comment by homerjam** [comment]
I appreciate your intentions @galambalazs but I think you're overlooking how simple the project would become using @richpeck 's PR. In fact breaking down the project further would make it even easier to maintain and ensure its relevance going forward.

**Comment by gblazex** [comment]
It needs Grunt, it needs Babel, it needs a map file.

This is a simple one-file, couple-hundred-line-long project. 
Adding that much dependency in no way makes it _easier_ to maintain.

It's written in a compatible version of Javascript that works and will continue to work for a long time.

The dependencies above don't affect the project's relevance. It's relevance is only dependent upon how fast browsers will implement smooth scrolling natively. 

Which they are doing btw (with one notable exception: Safari).

**Comment by Enalmada** [comment]
+1.  Just switched my smoothscroll site to turbolinks and now I can't scroll anymore.  Out of the two I think I have to keep turbolinks but I think it will be a while before all browsers get scrolling done right so it is sad to have to choose.
