### ISSUE TITLE
Calling #link from another page

### ISSUE THREAD

**Issue by samuelbrooks** [galambalazs/smoothscroll-for-websites#34]
How can I tell the plugin to wait for the page to load before going to the section? Having an issue of it just landing in the middle of the page on any link when coming from another page.

**Comment by gblazex** [comment]
This is probably not the plugin you are using.
It doesn't animate anchor links.

This one is for mouse wheel smooth scrolling

**Comment by samuelbrooks** [comment]
Haha, should of checked the git before posting. Sorry!
