### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clientHeight' of undefined (like closed issue #22)

### ISSUE THREAD

**Issue by VDShark** [galambalazs/smoothscroll-for-websites#38]
I've got this problem too.
For example with plugin Fancybox.

Page: http://htmlstream.com/preview/unify-v1.9.4/feature_gallery.html
1) click on first image;
2) click again to get next image;
3) press various keys;

> smoothScroll.js:336 Uncaught TypeError: Cannot read property 'clientHeight' of undefined
> In latest version of smoothscroll - same result.

Tested on Chrome 50.0.2661.102 (got similar result on Safari, but not in that particular case)

**Comment by nxrighthere** [comment]
Find this line
`var elem = overflowingAncestor(activeElement);` 
and change it to
`var elem = overflowingAncestor(document.activeElement);`

**Comment by Enalmada** [comment]
+1

Just put smoothscroll on my site and now getting errors reported to me in my monitoring.

```
TypeError: Cannot read property 'clientHeight' of undefined
  at keydown (/ajax/libs/smoothscroll/1.4.4/SmoothScroll.min.js:1:5233)
```

**Comment by gblazex** [comment]
this will be fixed in the latest version. thanks!

**Comment by yearmfew** [comment]
> Find this line
> var elem = overflowingAncestor(activeElement);
> and change it to
> var elem = overflowingAncestor(document.activeElement);

I am having the same problem in my website. I tried this and it did not work.
