### ISSUE TITLE
Disable smoothscroll on Mac by default

### ISSUE THREAD

**Issue by Konfuze** [galambalazs/smoothscroll-for-websites#39]
Smooth scrolling works fancy on Windows, but large amount of users found smooth scroll in Mac browsers quite annoying.

Maybe you can make an option, something like `disableOnMac` set to `true` by default?

If needed, i can make a PR.

**Comment by gblazex** [comment]
Hi, thanks for reporting!

Do you mean mouse wheel or touchpad scrolling? 
Which browser? What kind of input device are you using?

**Comment by Konfuze** [comment]
Hi, thanks for response.

It's about touchpad (and magic mouse) scrolling in all browsers.

**Comment by gblazex** [comment]
Are you using the default settings?

Touchpad scrolling should be unaffected by SS 

https://github.com/galambalazs/smoothscroll-for-websites/blob/master/SmoothScroll.js#L41

**Comment by AndrewRayCode** [comment]
This library absolutely destroys scrolling experiences on OSX with a touchpad. For example [this site](http://davegoosem.net/maya/texturing-maya/baking-lighting-into-a-texture-in-maya/) uses smoothscroll and the scrolling is a nightmare.

**Comment by inspyrenz** [comment]
Agreed with the comments above. Scrolling on OSX (trackpad, magic mouse) in Chrome and Safari is about as much fun as a colonic irrigation. Firefox is alright. Has always been an issue with all smooth scroll libraries I've found

**Comment by gblazex** [comment]
Guys just tested on Chrome & Safari under Sierra. Using a Retina Macbook Pro's touchpad I see no effect whether SS is running or not.

If you have a specific test site set up show me, but I'm skeptical to say the least.

**Comment by gblazex** [comment]
maybe you had touchpadSupport = true.
I now removed that option

**Comment by AndrewRayCode** [comment]
Go to the example site I linked and try to scroll. It's absolutely destroyed.

**Comment by inspyrenz** [comment]
Andrew3RayCode's website above scrolls me nearly 100vh when I move my finger even slightly on magic mouse or trackpad. An equivalent scroll on any other website scrolls about 30px. A normal sized scroll moves the page 200-300vh+.

unsure why you're skeptical (to say the least) @galambalazs with such an obvious bug and multiple people confirming it...

**Comment by gblazex** [comment]
That site is using an outdated version of the library.

I understand your concern guys that's why SS is built to leave touchpads unaffected. 

It's up to the website owners to update their versions now.

If you have issues with other websites reopen and I'll examine the version but it's no longer an issue with the current one.
