### ISSUE TITLE
Could it clash with the Chrome extension?

### ISSUE THREAD

**Issue by stereokai** [galambalazs/smoothscroll-for-websites#4]
What would happen if I put this script on my website, and a user has installed the Chrome extension?

**Comment by gblazex** [comment]
The best way is to try it out :)

The one which runs first wins.

It only matters in terms of settings though.

There was an issue same as this opened and the OP found it works great.

**Comment by stereokai** [comment]
Yeah.. I think it would be wiser to take a stance - and force the extension into a specific behaviour: will you give the power to the users (extension settings prevail) or the website owners (extension detects script and turns off for this webpage)?

**Comment by gblazex** [comment]
Preferably the user should decide.
Then again I'm not really keen on making the code more complicated (the website version has to travel through the network).

But if you have something simple in the works, PRs are welcome.

**Comment by stereokai** [comment]
It's pretty simple actually - and this addition should live only in the extension. The only new functionality introduced is:
1. Extension detects if website loads smoothscroll
2. Overwrites website settings
3. Regardless if the extension has already loaded its own smoothscroll or not, it loads it with its own settings

**Comment by gblazex** [comment]
Again PRs are welcome. :)

This is a low prio issue and I don't have a lot of time right now.

You have to keep in mind that for point (1) (_Extension detects if website loads smoothscroll_) you have to have something in place for the Website version which the Extension can detect.

Also that it can't be something simple like a global variable, because Chrome extensions live in a separate context.

The best way is probably through the DOM (e.g. adding a class to `<body>`) or `window.postMessage`, etc.

**Comment by Shakil-Shahadat** [comment]
The extension can check if there are any script tag with a 'src' attribute of 'smoothscroll' exists. 'smoothscroll' should be checked via regex, cause people can add version number with it.

It may not conflicting now, but it might in the future. Thanks for your time @galambalazs

**Comment by gblazex** [comment]
That's not really fool proof because:

a) the script may be renamed
b) the script may be part of a concatenated/combined bigger source file

**Comment by stereokai** [comment]
I agree with @galambalazs, and want to add, that instead, the extension would do better to detect the scrolling effect, rather than relying on traditional script detection methods.
