### ISSUE TITLE
Smooth scrolling breaks over iframes

### ISSUE THREAD

**Issue by native-apps** [galambalazs/smoothscroll-for-websites#42]
Hey there. Not sure if this is a conflict on my end. Is this a known or common issue? Love this script btw.

**Comment by gblazex** [comment]
No it should work with iframes.

Sample page?

**Comment by nativeimaging** [comment]
Sure! Thanks for the quick response.
This page has facebook comments loading in an iframe: https://www.nativeimaging.com/blog/seo-companies-the-good-the-bad-the-ugly/

Also, the home page has a video: https://www.nativeimaging.com/

**Comment by native-apps** [comment]
I couldn't figure out the cause for the issue. Still no luck.

**Comment by gblazex** [comment]
Yes this is since Chrome 51

See: https://www.chromestatus.com/feature/5678869528969216
https://bugs.chromium.org/p/chromium/issues/detail?id=564042

**Comment by gblazex** [comment]
I'll post an update but it'll only work if you load SmoohtScroll inside the iframes as well.
(cannot do anything about 3rd party iframes at the moment unfortunately)

**Comment by gblazex** [comment]
this should be fixed now, closing

**Comment by PavelGonzales** [comment]
Any news guys?
@galambalazs

**Comment by gblazex** [comment]
not fixed for you? are you loading SS in all your iframes?
