### ISSUE TITLE
Does not work on IE edge latest 

### ISSUE THREAD

**Issue by danyj** [galambalazs/smoothscroll-for-websites#43]
This used to work in edge but lately it does not , 
version

![screenshot_11](https://cloud.githubusercontent.com/assets/2340172/17572054/11de07dc-5f53-11e6-8cc5-f081305ee14f.jpg)

**Comment by julienetie** [comment]
Just tried it using Edge 14 via Browserstack
(Edge 34.14300.1000.0) Seems to be working.

**Comment by gblazex** [comment]
thanks. reopen if you have more data

**Comment by danyj** [comment]
This is definitely a no go on edge , no errors but the scroll is same as default , choppy. 
In Chrome , FF, Opera works fine
version http://prntscr.com/dbkuuk

**Comment by gblazex** [comment]
I'll check when I have a Windows computer at hand :-)
