### ISSUE TITLE
Smoothscroll breaks on OSX Sierra

### ISSUE THREAD

**Issue by TiagoDeSousa** [galambalazs/smoothscroll-for-websites#48]
Since I updated to OSX Sierra smoothscroll acts a bit weird on Chrome on mousewheel.

**Comment by sergiokag** [comment]
I have the same experience with OS X El capitan

**Comment by gblazex** [comment]
just chrome or safari too?

**Comment by TiagoDeSousa** [comment]
It happens in both to me.

**Comment by gblazex** [comment]
Can you do a Quick Time screen recording for me that showcases what you guys mean by weird.

Thanks

**Comment by gblazex** [comment]
duplicate of https://github.com/galambalazs/smoothscroll-for-websites/issues/16
