### ISSUE TITLE
Strange behavior <div style="position: absolute; z-index: -10000; [...]> in Chrome.

### ISSUE THREAD

**Issue by kostiantyn-petlia** [galambalazs/smoothscroll-for-websites#49]
Strange behavior `<div style="position: absolute; z-index: -10000; [...]>` in Chrome (v.53.0.2785.143 m).

If to collapse the bootstrap panel "Profile" in this page:
http://ukrainian-wife.com/en/user_profile/profile-f-419-en/

I see space after footer because this `<div>` does not update height: http://prntscr.com/crh5gs
If to disable SmoothScroll the `<div>` will disappear and all is OK. (v.1.4.0 & 1.4.4).
How can I fix it?

But FF & Edge - OK. And why `<div>` not present in FF & Edge?

**Comment by gblazex** [comment]
it'll be fixed in the next version thanks
