### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [galambalazs/smoothscroll-for-websites#5]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com/.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5443

**Comment by gblazex** [comment]
added in https://github.com/galambalazs/smoothscroll-for-websites/commit/ad93fb2b4f4d9b60e463e876a3c7bb38ffb17709

**Comment by gblazex** [comment]
@maruilian11 Can I change the "name" entry in my `package.json` (to "smoothscroll-for-websites" instead of "smoothscroll")?

I'd like to publish it as an `npm` repo and the "smoothscroll" name is taken.

How can we resolve this and still keep it working with cdnjs?

**Comment by maruilian11** [comment]
@galambalazs it's ok~ just open an issue on cdnjs after you changed the name.
we will send commits to keep it working :+1:
