### ISSUE TITLE
on full document load, scrolls to top of page/scroll location when refreshed/loaded

### ISSUE THREAD

**Issue by baesik** [galambalazs/smoothscroll-for-websites#51]
Hello,

It's a common practice for people to start scrolling a page before it has loaded. Doing so with this script will force the client to "teleport," or instantly scroll, up to either the top of the page or where the page was when refreshed. 
For example, if a website has lots of images to load and a user scrolls, every time an element is loaded, the page will scroll back up to the top. Once the entire page is loaded it will also scroll up to the top instantly.

**Comment by gblazex** [comment]
Which browser is this?
Can you also give a webpage  example?

I've never seen anything you are describing.
