### ISSUE TITLE
How to install this? Im a newbie here!

### ISSUE THREAD

**Issue by manojfedx** [galambalazs/smoothscroll-for-websites#52]
Hello ! I don't know how to install smooth scroll from zip? 
Im running Sierra 10.12 now!!
Please can anyone help me out with steps?

**Comment by gblazex** [comment]
are you making websites? this is page for website developers.

If you are a regular user other versions exist.

Also available as a Mac app
  http://www.smoothscroll.net/mac/

Or as a Chrome extension
  https://chrome.google.com/webstore/detail/smoothscroll/nbokbjkabcmbfdlbddjidfmibcpneigj

And Opera extension
  https://addons.opera.com/extensions/details/smoothscroll-3/
