### ISSUE TITLE
Scroll issues with Safari and Mozilla Firefox

### ISSUE THREAD

**Issue by ghost** [galambalazs/smoothscroll-for-websites#53]
Hello,

I'm a web developer from India. I'm using smoothscroll.js for my website but there is an issue. When i check my website through Safari or Mozilla Firefox scroll doesn't work but when i press down arrow key then scroll works for both.

Please can you help me ?

**Comment by gblazex** [comment]
show me the website

**Comment by ghost** [comment]
http://fruitbowllabs.com/alaukik/Branding-Innovations.html
http://fruitbowllabs.com/alaukik/Film-Production.html
http://fruitbowllabs.com/alaukik/Events-Entertainment.html
http://fruitbowllabs.com/alaukik/About-Us.html

**Comment by gblazex** [comment]
okay first of all disable touchpad support. 

'touchpadSupport = false' inside defaultOptions

then report back

**Comment by ghost** [comment]
okay. I'll do that and update you.

**Comment by ghost** [comment]
I disabled touchpad support inside defaultOptions. Now next ?

**Comment by gblazex** [comment]
Remove the SmoothScroll script and check scrolling on your website.
I can't scroll with Firefox!

I think your website is bugged without SmoothScroll.

It has nothing to do with this library.
