### ISSUE TITLE
Destroys scrolling on OSX

### ISSUE THREAD

**Issue by AndrewRayCode** [galambalazs/smoothscroll-for-websites#54]
This site http://permadi.com/1996/05/ray-casting-tutorial-2/

Has this source script: http://permadi.com/wp-content/themes/maskitto-light/js/smoothscroll.js?ver=4.2.10

Scrolling on OSX (chrome, at least) is destroyed. Scroll velocity is nightmarish and jumps the page.

**Comment by gblazex** [comment]
That is an old version.

Contact the website owner to update the library
