### ISSUE TITLE
Scrolling and hover together does't work

### ISSUE THREAD

**Issue by MorrisRuschel** [galambalazs/smoothscroll-for-websites#56]
When user is scrolling, hover event disable.
And the animation (CSS) stop and start again, only after user move the cursor.

**Comment by gblazex** [comment]
Which browser?

**Comment by MorrisRuschel** [comment]
Google Chrome - version 56.0.2924.87 - Windows 7 x64

**Comment by gblazex** [comment]
can you provide an example page?
