### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event.

### ISSUE THREAD

**Issue by ghost** [galambalazs/smoothscroll-for-websites#58]
Hi,

Your Javascript produces a Jank Error in Google Chrome V62. See error:

`[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

The error is pointing to the line of code referencing the "**addEventListener**"

I just thought I'd let you know.

**Comment by gblazex** [comment]
that is how the extension works
overriding default behavior
