### ISSUE TITLE
add tags for each version

### ISSUE THREAD

**Issue by maruilian11** [galambalazs/smoothscroll-for-websites#6]
would you please consider adding tags for each version so that we can add your lib on https://cdnjs.com/ **with git autoupdate**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5217

**Comment by gblazex** [comment]
added https://github.com/galambalazs/smoothscroll-for-websites/tags

**Comment by maruilian11** [comment]
thank you!
