### ISSUE TITLE
1.2.1 -> 1.4.1 incompatibilities?

### ISSUE THREAD

**Issue by rulatir** [galambalazs/smoothscroll-for-websites#63]
I am trying to npmify my project's dependency on SmoothScroll, but the project currently uses 1.2.1 while the oldest version on npm is 1.4.1, and the release log on github only dates back to 1.3.8. The information on possible incompatible changes between 1.2.1 and 1.3.8 is therefore unavailable, so the only way is to ask the author: can I just drop 1.4.1 in place of 1.2.1?

**Comment by gblazex** [comment]
in case you're not using any API's (like destroy) yes it should work all the same.
