### ISSUE TITLE
Safari 12.0.1 doesn't work

### ISSUE THREAD

**Issue by LucaDb** [galambalazs/smoothscroll-for-websites#66]
Safari 12.0.1 MacOs 10.13.6 the script doesn't seem to work. It's running but whit a normal wheel mouse the scroll behavior looks jumpy.

This is the best smooth scroll script i've ever tried!

Thanks

**Comment by LucaDb** [comment]
The issue seems related to this line
`isDivisible(event.wheelDeltaY, 120)`

Always returning false on Safari 12 Os 10.13.6
Hope this helps

**Comment by gblazex** [comment]
yes safari sends scroll values that are non uniform e.g. 3, 43, 12, 4, 5

SmoothScroll cannot currently handle these.

It only knows browsers that send events that are uniform e.g.: 120, 120, 120, -120, -120
or 360, 360, 360, -360, 360

**Comment by vladimirpikul** [comment]
So, is there gonna be a solution? Really need it...

**Comment by gblazex** [comment]
duplicate of #16

**Comment by gblazex** [comment]
there might be but havent been working on it yet
