### ISSUE TITLE
Errors when trying to use the wheel function in the mouse

### ISSUE THREAD

**Issue by ghost** [galambalazs/smoothscroll-for-websites#67]
I'm getting the following error in Chrome V73+:

## The Issue

Google has updated their Browser policy with regards to mouse wheel events see here: https://developers.google.com/web/updates/2019/02/scrolling-intervention

## The error in this github repo

Dev-Tools says the following error:

`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

Link ref: https://www.chromestatus.com/features/6662647093133312

This is your plugin error in Chrome V74:

![error](https://user-images.githubusercontent.com/17784082/53898831-c50bbf00-4030-11e9-8316-b50a2a34a030.png)

## Solution

I did some research and Googler's RByers has repeatably given the same answer throughout the web which I will add some links of his comments:

https://stackoverflow.com/questions/42101723/unable-to-preventdefault-inside-passive-event-listener/42288386#42288386

https://github.com/oliviertassinari/react-swipeable-views/issues/183#issuecomment-280537197

The solution by many other scrolling scripts has been to do the following:

Either adding `touch-action: none` or `touch-action: manipulation` for more info see here: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Google's direct link to the solution is here: https://developers.google.com/web/updates/2017/01/scrolling-intervention#breakage_and_guidance

The above link is also linked in their "**Making wheel scrolling fast by default**" web page as a solution.

**Comment by kubiqsk** [comment]
Hello, you can not combine fullpage.js with my plugin, that makes no sense

**Comment by ayumihamsaki** [comment]
@kubiqsk

I don't want to combine fullpage.js ??? That is a different scrolling script for one page platforms.

I want to fix smotthscroll error.

> If you're call preventDefault on every touchstart then you should also have a CSS rule to disable touch scrolling like (Quoted by Googler's RByers)

```css
.sortable-handler {
    touch-action: none;
}
```

That is the error you have.

**Comment by CarretPan** [comment]
Hello, I've fixed it for me. I changed the line 591

  window.addEventListener(type, fn, false);

by 

  window.addEventListener(type, fn, {passive: false});

As indicated at the end of https://developers.google.com/web/updates/2019/02/scrolling-intervention

I do not know if it's the best, but it works.

**Comment by gblazex** [comment]
fixed in the latest 1.4.9 version in a backwards compatible way.
