### ISSUE TITLE
API

### ISSUE THREAD

**Issue by TrySound** [galambalazs/smoothscroll-for-websites#7]
Need to add minimal API like `smoothScroll.init(options)` and `smoothScroll.destroy()`

**Comment by gblazex** [comment]
what's the use case?

**Comment by TrySound** [comment]
@galambalazs Setting options different of defaults.
Also this line repeated twice in the code

``` js
var options = defaultOptions;
```

**Comment by TrySound** [comment]
@galambalazs I use npm to load packages. And I'd like not to change source code.

**Comment by TrySound** [comment]
@galambalazs Also destroy method will be usefull on some conditions.

**Comment by TrySound** [comment]
Do you want I'll make a PR?

**Comment by gblazex** [comment]
Sure if you submit a PR I'll review it.

> Also destroy method will be usefull on some conditions.

again, what's the use case? :)

**Comment by TrySound** [comment]
On window resize if mobile destroy it.

**Comment by gblazex** [comment]
Can you expand?
I don't understand.

**Comment by TrySound** [comment]
@galambalazs Okay, I see mobile are not processed by this. But still it would be cool to control initialization. Just one function

``` js
smoothScroll(options);
```

**Comment by gblazex** [comment]
I'm open to make changes to the project but only if there's a good reason for them.
So far there hasn't been presented any.

**Comment by TrySound** [comment]
@galambalazs What if I want to use custom options, but if I use npm, I can't edit source files. Do you think it's not good reason?.

**Comment by gblazex** [comment]
You want to change the options. That's fair. I'll think about it.
Init and destroy doesn't seem useful to me.

**Comment by gblazex** [comment]
custom options and destroy were added
https://github.com/TrySound/smoothscroll-for-websites/commit/ad93fb2b4f4d9b60e463e876a3c7bb38ffb17709
