### ISSUE TITLE
Stuttering since last Chrome update

### ISSUE THREAD

**Issue by R3dRidle** [galambalazs/smoothscroll-for-websites#70]
Hello,

When using this tool we get a JS error since the last Chrome update:
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

This causes the scroll to stutter. Please advice or help with a fix.
Hope to hear from you.

**Comment by bUxEE** [comment]
Yep same here

**Comment by R3dRidle** [comment]
Looks like 1.4.9 fixes the issue by the way. Can you too confirm this?

**Comment by bUxEE** [comment]
I will update tonight and let you know

**Comment by KirDontsov** [comment]
Waiting for fixes

**Comment by 0xFrann** [comment]
Any solution?

**Comment by TemaSM** [comment]
**Chrome**:  v73.0.3683.86
**smoothscroll**: v1.4.9
For me stuttering was fixed by upgrading from v1.4.8 to v1.4.9, so now works just fine 👍

**Comment by gblazex** [comment]
also updated on npm now

**Comment by jimmy927** [comment]
It seems that an old Smoothscroll.js (1.4.0) is included in an Wordpress Theme "intact" [1.8.1] ( https://themeforest.net/item/intact-premium-multipurpose-wordpress-theme/19533865 ) leading to the exact same problem. Replacing the SmoothScroll.js on the wordpress server to 1.4.9 solves the issue.

**Comment by gblazex** [comment]
If you contact the author to update the theme I’ll be eternally grateful bro, thanks


Blaze
