### ISSUE TITLE
You need to remove the event.keyCode because it's Deprecated

### ISSUE THREAD

**Issue by ghost** [galambalazs/smoothscroll-for-websites#74]
Hi,

You use `event.keyCode` four times and you should replace it with the `event.key` instead.

Deprecated: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Change to this: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key

**Comment by pwoidke** [comment]
Created PR with fix: https://github.com/gblazex/smoothscroll-for-websites/pull/105

**Comment by gblazex** [comment]
thank you guys, fixed
