### ISSUE TITLE
Can't control an element with overflow-y: scroll smoothly

### ISSUE THREAD

**Issue by JarvisChao** [galambalazs/smoothscroll-for-websites#77]
When moving the mouse over an element with overflow: scroll, it can't quickly change the scrollbar control.
Is there any way to improve? It is not really good for UX.
Thanks~

**Comment by gblazex** [comment]
can you post an example?

**Comment by JarvisChao** [comment]
Sorry, it's my mistake to change 'animationTime' over than 1s.
So when moving the mouse over an element with overflow: scroll, it have to wait for 1s to change scrollbar control.
