### ISSUE TITLE
Is it possible to release a non-keyboard control version

### ISSUE THREAD

**Issue by ghost** [galambalazs/smoothscroll-for-websites#78]
Hi,

I'm in the process of adding WAI-ARIA keyboard navigation to my forms, menu's etc. The trouble is that I'm having a major conflict with your smoothscroll code.

When I select the menu container and press `home` and `end` for the menu options your smoothscroll is over-writing the WAI-ARIA javascript code. It seems like your code is not isloated enough.

Would it be possible to release a lite version / non-keyboard control version.

I basically want to do the following setup:

1. Use your smoothscroll for mouse control (mouse clicks and mouse wheel) and not keyboard control.
2. Use WAI-ARIA on each section with keyboard control. This will be fully isolated to certain keys and container classes - so no conflicts.

Let me know,

Thanks.

**Comment by ayumihamsaki** [comment]
Sorry closing this I forgot to add `event.preventDefault();` to my code. Works fine with your code now.

**Comment by ghost** [comment]
Closing this, I forgot to add `event.preventDefault() `to my code.
