### ISSUE TITLE
Latest opera issue

### ISSUE THREAD

**Issue by danyj** [galambalazs/smoothscroll-for-websites#8]
Opera update was released yesterday, after that site scroll is completely disabled.

My options 

```
var defaultOptions = {

    // Scrolling Core
    frameRate        : 150, // [Hz]
    animationTime    : 800, // [ms]
    stepSize         : 120, // [px]

    // Pulse (less tweakable)
    // ratio of "tail" to "acceleration"
    pulseAlgorithm   : true,
    pulseScale       : 8,
    pulseNormalize   : 1,

    // Acceleration
    accelerationDelta : 50,  // 50
    accelerationMax   : 1,   // 3

    // Keyboard Settings
    keyboardSupport   : true,  // option
    arrowScroll       : 50,    // [px]

    // Other
    touchpadSupport   : true, // ignore touchpad by default
    fixedBackground   : true, 
    excluded          : ''    
};
```

Any help is appreciated.

**Comment by gblazex** [comment]
i can check this on monday. thanks for the report

**Comment by gblazex** [comment]
Works for me in latest Opera Stable 31.0.1889.174

**Comment by danyj** [comment]
Opera/9.80 (Windows NT 6.2; WOW64) Presto/2.12.388 Version/12.17

win 10 
http://prntscr.com/8c4hx6

**Comment by danyj** [comment]
There was another update today , works now, whatever it was win10 is a mess for other browsers

**Comment by danyj** [comment]
still ongoing ,   bare html5 file with smooth in it and  < br />  no js no jquery nothing

with 

```
var initDone  = true;
```

it works ,  but it is set to false by default

v 31.0   browser profile  

Version:    31.0.1889.174 - Opera is up to date
Update stream:  Stable
System: Windows 10 64-bit (WoW64)
Browser identification

Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174

**Comment by danyj** [comment]
and now if that is set to true in chrome I get 

```
ty 'nodeName' of undefined
```

line 541  

```
function isNodeName(el, tag) {
    return (el.nodeName||'').toLowerCase() === tag.toLowerCase();
}
```

**Comment by gblazex** [comment]
I don't understand what should happen with an empty file and a BR tag?

**Comment by danyj** [comment]
multiple br tags to stretch the page, not one ,   basically there is nothing in there that could cause conflict ,

**Comment by gblazex** [comment]
ok I'll check
