### ISSUE TITLE
Doesn't make any scroll 

### ISSUE THREAD

**Issue by mrk197702** [galambalazs/smoothscroll-for-websites#80]
Hello
it's not scrolling while usually it works. I removed overflow-x: hidden from body but it's the same
Wht's the problem? thanks

**Comment by mrk197702** [comment]
The WP plugin didn't work but pure js version worked

**Comment by gblazex** [comment]
can you please contact the WP plugin to update their version of SS, thank

**Comment by kubiqsk** [comment]
Hi,
@gblazex - in this plugin https://wordpress.org/plugins/mousewheel-smooth-scroll/ there is already version 1.4.10
@mrk197702 - try to resave your settings, maybe it will help, or take a look in console, if there are some errors ;)

**Comment by mrk197702** [comment]
@kubiqsk no man, no errors in my console I usually look at it ;)

**Comment by kubiqsk** [comment]
@mrk197702 so not even re-save of settings helped? You can contact me on forum, or by email (info@kubiq.sk), let me know there what is your browser and version, OS and version, your web URL and I can take a look

**Comment by mrk197702** [comment]
Hi, in the meanwhile I had js version, but disabling it and reinstalling the plugin now works, , thanks, .but when I tried few weeks ago I had to use js version because WP plugin didn't work for me
