### ISSUE TITLE
Is there a way to activate it even on firefox?

### ISSUE THREAD

**Issue by iamalessiopaoletti** [galambalazs/smoothscroll-for-websites#81]
I wish I could also activate it on firefox. is there a way?

**Comment by gblazex** [comment]
not unless you ship a modified version.

it should be one line of code change:
https://github.com/gblazex/smoothscroll-for-websites/blob/master/SmoothScroll.js#L746

**Comment by adamcoulombe** [comment]
@gblazex just curious.. is there a reason this isnt on for firefox by default?

**Comment by drinkmaker** [comment]
> @gblazex just curious.. is there a reason this isnt on for firefox by default?

Firefox has a fairly smooth default scrolling.

**Comment by adamcoulombe** [comment]
@drinkmaker but not buttery smooth 😄

**Comment by adamcoulombe** [comment]
thanks @gblazex for the great script, it makes adding smooth scroll to any web page super easy.

**Comment by iamalessiopaoletti** [comment]
thanks for the reply!
for to clarify, this:

`
var userAgent = window.navigator.userAgent;
var isEdge    = /Edge/.test(userAgent); // thank you MS
var isChrome  = /chrome/i.test(userAgent) && !isEdge; 
var isSafari  = /safari/i.test(userAgent) && !isEdge; 
var isMobile  = /mobile/i.test(userAgent);
var isIEWin7  = /Windows NT 6.1/i.test(userAgent) && /rv:11/i.test(userAgent);
var isOldSafari = isSafari && (/Version\/8/i.test(userAgent) || /Version\/9/i.test(userAgent));
var isEnabledForBrowser = (isChrome || isSafari || isIEWin7) && !isMobile;
`

will be

`
var userAgent = window.navigator.userAgent;
var isEdge    = /Edge/.test(userAgent); // thank you MS
var isChrome  = /chrome/i.test(userAgent) && !isEdge; 
var isSafari  = /safari/i.test(userAgent) && !isEdge; 
var isFirefox  = /firefox/i.test(userAgent) && !isEdge; 
var isMobile  = /mobile/i.test(userAgent);
var isIEWin7  = /Windows NT 6.1/i.test(userAgent) && /rv:11/i.test(userAgent);
var isOldSafari = isSafari && (/Version\/8/i.test(userAgent) || /Version\/9/i.test(userAgent));
var isEnabledForBrowser = (isChrome || isSafari || isFirefox || isIEWin7) && !isMobile;
`
?

**Comment by gblazex** [comment]
Something like that yes.

I still recommend against doing it as it breaks default behavior.

It’s only a good trade off of the default behavior is shit.

Firefox scrolling is passable 


Blaze
