### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by hemant7405** [galambalazs/smoothscroll-for-websites#84]
Hello,

I am facing the preventDefault issue on chrome when I scroll using a mouse wheel, JS errors appear each time the mouse wheel is moved. Is this is a known issue?

Looking forward to hearing from you.

**Comment by snix0** [comment]
This issue should be fixed with v1.4.9, where a change was made to support the new standard of some event listeners being passive by default starting from Chrome 73.

You can read more about it from Google here: 
https://developers.google.com/web/updates/2019/02/scrolling-intervention

**Comment by gblazex** [comment]
it should work as snix0 said. if you still experience problems please provide sample page/code.
